# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-17 22:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_camera', models.CharField(blank=True, choices=[('canon', 'Canon'), ('nikon', 'Nikon'), ('sony', 'SONY')], default='', max_length=35, null=True)),
                ('type_photography', models.CharField(blank=True, choices=[('Nature', 'Nature'), ('Photography', 'Photograpy/Newborn'), ('6 Months', '6 Months'), ('BabyPics', 'Baby Pics'), ('Maternity', 'Maternity'), ('Babies', 'Babies')], default='', max_length=35, null=True)),
                ('employable', models.BooleanField(default=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('bio', models.CharField(blank=True, max_length=800, null=True)),
                ('personal_website', models.URLField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=12, null=True)),
                ('travel_radius', models.IntegerField(blank=True, null=True)),
                ('imager_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            managers=[
                ('active', django.db.models.manager.Manager()),
            ],
        ),
    ]
