# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 21:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImagerProfile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagerprofile',
            name='type_camera',
            field=models.CharField(blank=True, choices=[('canon', 'Canon'), ('nikon', 'Nikon'), ('sony', 'Sony')], default='', max_length=35, null=True),
        ),
    ]
