# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 23:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ImagerProfile', '0002_auto_20170215_1338'),
        ('imager_images', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='albums',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='albums',
            name='photos',
        ),
        migrations.RemoveField(
            model_name='albums',
            name='user',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='select_cover',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='upload',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='user',
        ),
        migrations.AddField(
            model_name='albums',
            name='cover_image',
            field=models.ImageField(null=True, upload_to='images/cover_photos'),
        ),
        migrations.AddField(
            model_name='albums',
            name='date_uploaded',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='albums',
            name='images',
            field=models.ManyToManyField(related_name='albums_of_photos', to='imager_images.Photo'),
        ),
        migrations.AddField(
            model_name='albums',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='ImagerProfile.ImagerProfile'),
        ),
        migrations.AddField(
            model_name='photo',
            name='image_file',
            field=models.ImageField(default=datetime.datetime(2017, 2, 24, 23, 26, 38, 41638, tzinfo=utc), upload_to='images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photo',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photo', to='ImagerProfile.ImagerProfile'),
        ),
        migrations.AlterField(
            model_name='albums',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='albums',
            name='date_published',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='albums',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='albums',
            name='published',
            field=models.CharField(choices=[('private', 'Private'), ('shared', 'Shared'), ('public', 'Public')], default='private', max_length=15),
        ),
        migrations.AlterField(
            model_name='albums',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='photo',
            name='date_published',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='photo',
            name='published',
            field=models.CharField(choices=[('private', 'Private'), ('shared', 'Shared'), ('public', 'Public')], default='private', max_length=15),
        ),
        migrations.AlterField(
            model_name='photo',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
